security: 
  user: 
    password: admin
    name: admin
  basic:
    enabled: false

eureka:
  client:
    ## 关闭心跳检测
    registerWithEureka: false
    fetchRegistry: false
      
spring:
  datasource:
    initialize: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: ikfa
    password: ikfa
    platform: h2
    # 指定插入数据库语句的脚本位置  
    data:
    - classpath:testdatas/data-h2.sql
    - classpath:testdatas/data-h2-dict.sql
    # 指定生成数据库的schema文件位置  
    schema:
    - classpath:testdatas/schema-h2.sql
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  boot:
    admin:
      url:
      - http://localhost:8082
  data:
    rest:
      base-path: /admin

# 所有运维支持类的 Rest
management:
  endpoints:
    web:
      exposure:
        include: "*"   

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000000
# 设置 hystrix.shareSecurityContext 属性为true。设置这个值会自动配置一个Hystrix兵法策略会把securityContext从主线程传输到你使用的Hystrix command
hystrix.shareSecurityContext: true




ikfa: 
  file-upload:
   path: E:/work/sys_project/sys-manege-new/sys-manager/sys-admin-pages/
  refresh: 
   resource: 
     cron: 0 0/30 *  * * ? 
  security:
    authentication:
      path: /login
      refresh: /refresh/token
      # 生产环境应当适当裁剪
      permiturl: /, /*.html, /favicon.ico, /**/*.html, /**/*.css, /**/*.js,/refresh/token,/h2-console,/api/v1/login,/getVlidateCode
      jwt:
        iss: taikang
        header: Access-Token
        # 秘钥不同项目自行配置解析 token 时使用
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours，根据实际项目调整 token 的有效时间单位秒
        token-validity-in-seconds: 99999999999986400
        token-validity-in-seconds-for-remember-me: 9999992592000
    swagger-ui:
      test:
        # 是否开启swagger-ui页面测试功能  ture 开启，false 关闭 生产环境应该关闭
        enable: true
        # 开启swagger-ui页面测试功能时模拟的 token
        mocktoken: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzeXNhZG1pbiIsImF1ZCI6IndlYiIsImF1dGgiOiJhZG1pbiIsImlzcyI6InRhaWthbmciLCJleHAiOjc3NjYyODExNDc2ODE4MTUsInVzZXIiOiJ7XCJhY2NvdW50Tm9uRXhwaXJlZFwiOnRydWUsXCJhY2NvdW50Tm9uTG9ja2VkXCI6dHJ1ZSxcImF1dGhvcml0aWVzXCI6W3tcImF1dGhvcml0eVwiOlwiYWRtaW5cIn1dLFwiY3JlZGVudGlhbHNOb25FeHBpcmVkXCI6dHJ1ZSxcImVtYWlsXCI6XCJcIixcImVuYWJsZWRcIjp0cnVlLFwiaGVhZEltYWdlXCI6XCIvdXBsb2FkL2ltYWdlLzIwMTcxMjEyLzQ5MDE1MTMwNjQxMTMyOTIuanBnXCIsXCJpZFwiOlwiMTM1NFwiLFwicGFzc3dvcmRcIjpcIiQyYSQxMCRDMDJxcy42bDVzeE12b2RzOGhBWVlPcWxFdjc4VzE4ejVkNkw0RUFsVXFIMDZYbjNZcFRnNlwiLFwidWNvZGVcIjpcInN5c2FkbWluXCIsXCJ1aWRcIjpcIjEzNTRcIixcInVuYW1lXCI6XCJzeXNhZG1pblwiLFwidXNlcm5hbWVcIjpcInN5c2FkbWluXCJ9IiwiaWF0IjoxNTE2MjQzMTczfQ.Z0UKzw_CHnAabPZbJSvAnr0aYm_FPFVACXYWeHS7yp2RMnFi8weR8b7MJ3YRNA2UJPbbMo1A4xS7Aa4QVj55BA

redis:
  hostName: 10.130.209.11
  password: taikang
  port: 6379
  maxWaitMillis: -1 
  lifo: true
  minEvictableIdleTimeMillis: 1800000
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: -1
